### ISSUE TITLE
Adding new Camel logo

### ISSUE THREAD

**Issue by AlvaroBus** [opensourcedesign/jobs#116]
Hello Claus and All,
Attached my offer of new Camel logo.
If you think about it, would be good to
remove some object or so, please tell
me and i will do it.
Hope you like it.
Best regards

Alvaro

![400x160 con sol blanco](https://cloud.githubusercontent.com/assets/23473270/20301152/8423a552-ab22-11e6-9531-e29d9ccd65c4.jpg)
![sin sin](https://cloud.githubusercontent.com/assets/23473270/20301160/8ed37b94-ab22-11e6-9aeb-6a1870a47bed.png)
![con sin](https://cloud.githubusercontent.com/assets/23473270/20301169/97c5ea8e-ab22-11e6-9d79-ed4a50254686.png)

**Comment by evalica** [comment]
Related issue #108
