### ISSUE TITLE
Truncated Titles are Useless

### ISSUE THREAD

**Issue by Miserlou** [opensourcedesign/jobs#129]
All of the titles are being truncated to the point of unreadability.

Ex:
"Create a Logo for a large O"
"Create a logo for open sourc"
"Create a logo for awesom"
"Designer For Offline-First, P"

Literally every title over 4 words is useless and needs to be clicked on to learn more.

Also, while we're at it: Two columns is a really bad way to lay this information out, especially if there is no differentiation information between the two columns. If they were layed out in a single column, maybe you would have enough space to actually display the full titles.

**Comment by evalica** [comment]
Another solution would be to not include the organization in the title. 
Some posts follow this rule, but I guess the problem is that there is no true rule in the metadatas displayed.

**Comment by simonv3** [comment]
I have wanted to change the two column layout for a while. I think that would be a great first step. 

@Miserlou is that something you'd have time to change?

**Comment by simonv3** [comment]
This has been fixed.
