### ISSUE TITLE
Several Organisation URL links are not working

### ISSUE THREAD

**Issue by evalica** [opensourcedesign/jobs#130]
For example: 
1. https://github.com/opensourcedesign/jobs/blob/gh-pages/jobs/2017-01-02-gnome-two-factor-auth.md
http://opensourcedesign.net/jobs/jobs/2017-01-02-gnome-two-factor-auth
the url is empty
`<a id="organization" class="organization" href="">Gnome TwoFactorAuth</a>`

The problem is that jobs layout displays 
`href="{{ page.org_url }}"`
while the job entry provides 
`organization_url: 'https://github.com/bil-elmoussaoui/Gnome-TwoFactorAuth'`

2. https://github.com/opensourcedesign/jobs/blob/gh-pages/jobs/2016-11-21-retroarch-assets.md
provides 
`url: http://www.libretro.com`

3. https://github.com/opensourcedesign/jobs/blob/gh-pages/jobs/2016-10-22-gngr-logo.md
etc. 

-----

First of all we need to: 
- [x] decide which version we want
- [x] make sure the template is correct
https://github.com/opensourcedesign/jobs/blob/gh-pages/job-template.md
currently it has
url: http://organisation-website.com
- [x] make sure the job form http://opensourcedesign.net/opensrcdesignjobs/ uses the correct param, currently is 'organization_url' instead of 'org_url'
- [x] make sure ALL the posts are using that field

WDYT?

**Comment by evalica** [comment]
Related to ab614a0c57105bd5f3b76833023dfac51387efff

**Comment by evalica** [comment]
So according to @simonv3 comment "Urls shouldn't be called 'url', which is reserved by Jekyll" I guess we should use "org_url" instead of "url". 

Current stats are: 
- 42 usages of "url"
- 12 usages of "org_url"
- 1 usage of "organization_url"
- 1 job withouth url at all

**Comment by simonv3** [comment]
Good sleuthing! We really messed that one up early on I guess?

**Comment by evalica** [comment]
Thanks @simonv3 I will close this issue as Fixed.
