### ISSUE TITLE
Add an expiration date for job posts

### ISSUE THREAD

**Issue by evalica** [opensourcedesign/jobs#131]
While usually we start having the need for this kind of functionality when we are flooded with posts (not quite yet, although we have 56 entries, from which 39 are searching), the problem we have is that: 
- we don't know if the job post is still active
- people from our organization might forget to mark a post as "closed"
- people that initially added the post might forget to close it in our repo. 

A solution would be to:
- allow people to add in the job template the expiration date;
- have a filter on the website and just display not expired job posts;
- have a listener and automatically change the status to "expired" if the date passed (although I don't think this is possible on the platform used). 

WDYT?

**Comment by bnvk** [comment]
@evalicia this is a great idea! Can you please move it to the
[core issues](/opensourcedesign/opensourcedesign.github.io/issues) repo?

**Comment by bnvk** [comment]
Moved issue to opensourcedesign/opensourcedesign.github.io#84
