### ISSUE TITLE
Add 'Role' to the jobs layout

### ISSUE THREAD

**Issue by evalica** [opensourcedesign/jobs#132]
Role information is missing when viewing a job post in detail. 

For example: 
<img width="451" alt="list-item" src="https://cloud.githubusercontent.com/assets/629552/21742588/a41450bc-d4fa-11e6-87c7-8655e9f6454b.png">

When looking at the details:
<img width="600" alt="item-detail" src="https://cloud.githubusercontent.com/assets/629552/21742599/c8a35482-d4fa-11e6-8347-d79e8223afad.png">

there is no mention that this is a "Logo Designer" role wanted.

Ideally we would need to have the "Role" mandatory in the job form, since we are using this information when listing the jobs. 

For example:
<img width="441" alt="missing-role" src="https://cloud.githubusercontent.com/assets/629552/21742606/024d6b78-d4fb-11e6-881f-5f5affad0099.png">
didn't provide at all the 'role', instead it entered the info in the title. 
Still having mandatory roles is needed by https://github.com/opensourcedesign/opensourcedesign.github.io/issues/70 in order to be able to filter.

**Comment by evalica** [comment]
Also we are missing from the job layout the new 'how_to_apply' and 'skills' fields from the new form. Maybe the clean way is to create a new issue for this, but I'm mentioning it, since it's related. 

So for example, this is what we display:
<img width="500" alt="layout" src="https://cloud.githubusercontent.com/assets/629552/21742722/be972264-d4fc-11e6-847a-5ea7fe1476d3.png">

but we are missing all the important information (like how to contact), see
![contact](https://cloud.githubusercontent.com/assets/629552/21742727/e08a95cc-d4fc-11e6-92df-d822901c2a8a.png)

**Comment by simonv3** [comment]
Some bullets:
* [x] Add skills
* [x] Add how to apply
* [x] Add role in form and in view
* [x] Show description _&_ content

Am I missing anything @evalica?

**Comment by evalica** [comment]
- [ ] Add some spacing between metadata and description? (after How to apply)

**Comment by evalica** [comment]
It starting to be a lot of data to process (with the new metadata added) so we might want in the future to fix a bit the layout. Maybe most important metadata at the top, description and contact data after. Just an idea.

**Comment by evalica** [comment]
Also we have lots of 'undefined'. Maybe we can hide that from the display? See 
- http://opensourcedesign.net/jobs/jobs/2017-02-09-Intern%20UX-Design/Research
- http://opensourcedesign.net/jobs/jobs/2017-02-05-Usability%20Testing%20with%20coala
- http://opensourcedesign.net/jobs/jobs/2017-02-05-Repository%20configuration%20for%20code%20analysis%20as%20a%20service%20using%20coala
- http://opensourcedesign.net/jobs/jobs/2017-01-30-Graphic%20design%20for%20FOSSASIA%20conference%20(t-shirt%20+%20some%20artwork)
- etc.

**Comment by simonv3** [comment]
Yeah, I tried a couple of ways of filtering and hiding it but none of them worked. 

The issue was that the stuff that gets entered as the description wasn't getting parsed properly with staticman (https://github.com/eduardoboucas/staticman/issues/30) but that should be fixed now (I just did a test PR to see and it looks right). We should just remove the "undefined" from those jobs. 

I think ideally we'd also improve the URLs.

**Comment by bnvk** [comment]
@evalica i'm closing this issue as it seems somewhat resolved. The `undefined` bits seem to be artifacts from staticman submission (when no content was submitted, is that correct @simonv3 ? Also, i'm not seeing this any in newer postings (but those also have content).

In anycase, please re-open / file any specific web-dev things in the [opensourcedesign.github.io](/opensourcedesign/opensourcedesign.github.io) repo as I'm trying to organize dev tasks a bit:

- Milestone - https://github.com/opensourcedesign/opensourcedesign.github.io/milestone/1
- Project - https://github.com/opensourcedesign/opensourcedesign.github.io/projects/1

**Comment by simonv3** [comment]
Yeah, undefined is what staticman submits if it doesn't get anything, which is a bit of a pain. Maybe we need to use JS on the front-end to set empty things to `null` rather than `undefined` before submitting the form?
