### ISSUE TITLE
Search for new Camel logo

### ISSUE THREAD

**Issue by AlvaroBus** [opensourcedesign/jobs#181]
Hello, this is my contribution in the search of a new Camel logo.

![camel_logo_alvaro_bustos](https://cloud.githubusercontent.com/assets/23473270/23662840/1082233a-0351-11e7-846a-7ddea0ed2069.png)

![camel_alvaro_bustos](https://cloud.githubusercontent.com/assets/23473270/23662847/18f35002-0351-11e7-96c8-8c823e70dc94.png)

Best regards
Alvaro

**Comment by simonv3** [comment]
Hey @AlvaroBus, thanks for your contribution! I think the Camel logo issue has been taken somewhere else? See ticket #108.

**Comment by AlvaroBus** [comment]
...well @simonv3, the ticket #108 is locked.
Could you please reopen this issue?
Thak you.
Alvaro

**Comment by AlvaroBus** [comment]
...well Simon, the ticket #108 is locked.

Could you please reopen the issue #181, and
tell me why you closed it after i've opened?
Thank you

Alvaro

...................

**Comment by simonv3** [comment]
Hey @AlvaroBus - that ticket is locked because the Camel community decided to re-evaluate their logo situation. Please reach out to them directly https://github.com/opensourcedesign/jobs/issues/108#issuecomment-265693747.
