### ISSUE TITLE
best practices: involving opensourcedesign in ongoing design efforts?

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/jobs#183]
**Scenario:** On twitter, I stumble upon a logo discussion at a project I like. There is no concensus on a design yet, only that they want a logo. 
Me and @elioqoshi were briefly involved and we thought about asking them to file a job. 

**Pro:** Sounds like something for us and new people get to know us. 
**Contra:** They are already discussing ideas and there is a high risk that there are at least two paralell discussions; since they are new to OSD, they are probably also most likely to not involve it as much as anything else.

What would be best practices here?

**Comment by bnvk** [comment]
> What would be best practices here?

1. Figure out who project owner / person involved w/ getting logo created is
2. Direct them to: http://opensourcedesign.net/jobs/job-form/
3. Encourage them adding helpful context about the job

**Comment by bnvk** [comment]
For the sake of organization, i'm closing this issue. In the future @jdittrich please open threads like this in [organization](/opensourcedesign/organization) repo with the **Discussion** label applied!
