### ISSUE TITLE
Design a logo for Jugaadfest

### ISSUE THREAD

**Issue by mariobehling** [opensourcedesign/jobs#195]
Please help us to design a logo for [Jugaadfest.com](http://jugaadfest.com), which will take place at the end of June in Hyderabad. We would like a simple logo preferable in a vector format (if possible svg) that embodies the idea of Jugaad as described below.

Background: Jugaad (alternatively Juggaar) is a colloquial Hindi (Devanagiri: जुगाड़, Latin: Jugāṛ), Urdu (Urdu alphabet: جگاڑ, Latin: Jugāṛ) and Punjabi word, which has various meanings depending on the situation. Roughly translated, jugaad is a "hack". It could also refer to an innovative fix or a simple work-around, a solution that bends the rules, or a resource that can be used in such a way. It is also often used to signify creativity—to make existing things work, or to create new things with meager resources. Jugaad is increasingly accepted as a management technique and is recognized all over the world as an acceptable form of frugal engineering at peak in India. https://en.wikipedia.org/wiki/Jugaad

Please follow up on the specific repository here: https://github.com/fossasia/jugaadfest.com/issues/3

@victoria-bondarchuk @spMohanty

**Comment by simonv3** [comment]
Hey @mariobehling! Thanks for posting this!

Do you think you could submit a job form for this? That way whomever is subscribed to the RSS feed and our twitter account will be able to share it.

http://opensourcedesign.net/jobs/job-form/

**Comment by jancborchardt** [comment]
Closing since as @simonv3 said we accept job submissions via our job form at http://opensourcedesign.net/jobs/job-form/ :)

Then they also show up directly on the site at http://opensourcedesign.net/jobs
