### ISSUE TITLE
It should be possible to interact/comment on each job

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/jobs#199]
Some big problems with the job board at the moment are:

- it’s very static, discussion is difficult to start
- you don’t know the state of it, if it’s taken already
- we don’t know if it’s done

As far as I know it’s possible to embed Discourse thread replies in a website. We could have a category in the Discourse called »Jobs« (you can’t create posts but will be led to the [job submission form](http://opensourcedesign.net/jobs/job-form/)), and one thread per job. Then on every job there’s the discussion thread below.
@erlend-sh could you point us how to do that maybe? :)

We do have to require that the people have to register at Discourse though and be subscribed to the issue. But maybe that can be automated and will lead to growth.

cc @jdittrich @simonv3 @belenbarrospena @janushead @guiguru @HeikoTietze @bnvk @evalica

**Comment by simonv3** [comment]
I like this idea a lot.

**Comment by belenbarrospena** [comment]
Sounds good to me too.

**Comment by jancborchardt** [comment]
Moved to https://github.com/opensourcedesign/opensourcedesign.github.io/issues/100 cause we have to many repositories – we’ll only use the website repo for website issues, _not_ the jobs repo. :)
