### ISSUE TITLE
Only show payment information if "we can pay" is choosen

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/jobs#200]
**Story:** I don't want to be distracted by fields I don't need
**Solution:** Only show payment information if "we can pay" is choosen

**Comment by m1guelpf** [comment]
I don't know why, but it reminds me of this xkcd...
![existential_bug_reports](https://cloud.githubusercontent.com/assets/23558090/25248308/0faccb06-260e-11e7-9596-a3f094ae71bf.png)

**Comment by belenbarrospena** [comment]
hehe. FWIW, what @jdttrich suggests was the original design. For some
reason, my javascript is broken or  got lost. Not surprising, given that I
know nothing about javascript :D

On Thu, Apr 20, 2017 at 8:12 PM, Miguel Piedrafita <notifications@github.com

**Comment by bnvk** [comment]
I disagree. It is helpful to know if a job pays or expects work to be done for free. How is not specifying that information helpful to letting a prospective designer know the terms of engaging in a job.

For future reference, please file issues pertaining to design & functionality of job board on the website repo and tag them with "job board" https://github.com/opensourcedesign/opensourcedesign.github.io/milestone/1

**Comment by jdittrich** [comment]
There are two fields: "Can you pay?" and "how much can you pay" – the latter only makes sense if the former is on "I can pay". Or do I get this wrong?

**Comment by belenbarrospena** [comment]
@bnvk I think you read this wrong. @jdittrich meant that the "How much you can pay?" field should only show when you select the "Paid" radio button in the "Compensation" question. Everybody will see that you have 2 compensation options (free and paid for), but only the people who choose the pay option will see the control to add information about how much they are paying. It's just a conditional control.

But yes, if this is not the right repo, it should be reopened in the right one.
