### ISSUE TITLE
Branching to specific forms for Hiring, specific Tasks, general interest

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/jobs#201]
There are different requirements for 

* Showing general openness to design contributors
* Hiring and paying people to work part/fulltime at your org
* Having a specific task to be done at your projects

They should have different forms so we can "nudge" towards meaningful informations.

**Comment by jancborchardt** [comment]
@jdittrich can you reopen this issue at https://github.com/opensourcedesign/opensourcedesign.github.io/issues – we want to keep all issues related to the website in the website repo, and not in the Jobs repo :)
