### ISSUE TITLE
Using Links in forms

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/jobs#204]
**User Story:** As a Job poster, I want to link relevant resources.

**Problem:** Linking seems to be only possible with Markdown and not all users are aware of that

**Possible solutions**
* Provide a link/link text section (+ generates proper links;  - not in text;  - more complex form)
* Autolink URL-like text 

**Example** [Libre Office Branding Job](https://github.com/opensourcedesign/jobs/commit/ac181891ad038560f5d7456e47f641f0dd114add) 

----------------
![image](https://cloud.githubusercontent.com/assets/3416487/25269425/e025f316-267c-11e7-9aec-30f9eb99deec.png)
-----------------

**Comment by bnvk** [comment]
Closing this as it pertains to the whole site and is a "web dev issue" thus, use the [website repo issues](/opensourcedesign/opensourcedesign.github.io/issues) please!
