### ISSUE TITLE
Preview <> Jobs Board, Changes after Merge

### ISSUE THREAD

**Issue by HeikoTietze** [opensourcedesign/jobs#208]
In https://github.com/opensourcedesign/jobs/pull/202 @jdittrich made some changes and me too later. Reason was basically that my lists starting with * were not recognized as such. But in particular I messed up later with links like `<a href="">Foo</a>` that are shown as expected in the github preview but not when the job is posted on the board. After merging it I've seen the problem but being not able to fix it. My try to change the file https://github.com/opensourcedesign/jobs/commit/62c25327909f96d98e591c9a4d7e9e39370739fb directly failed, likely because of missing access right, but that's a guess.
In the end I have no idea what happens to the job since the text is kind of scrambled on the board. It starts with pieces from the end, has varying fonts, and the links are not interactive. So besides the failed experiments to solve it myself the post needs some rework.

**Comment by jancborchardt** [comment]
@HeikoTietze please reopen the issue in our website issue tracker at https://github.com/opensourcedesign/opensourcedesign.github.io/issues – cause we want to have all issues related to the website (including job board) in our website issue tracker (less confusion where issues are ;)

Thanks and sorry! :)

**Comment by jancborchardt** [comment]
And it’s of course my mistake – I mentioned yesterday issues related to the job board go here but I was mistaken. :)

Also see the one issue now open which makes clear that we do not use this issue tracker: https://github.com/opensourcedesign/jobs/issues/207 ;)

**Comment by jancborchardt** [comment]
Ah sorry – this is actually related to a job. Reopening.

**Comment by HeikoTietze** [comment]
>jancborchardt commented 13 minutes ago 
>jancborchardt closed this 13 minutes ago
>jancborchardt reopened this 10 minutes ago
>jancborchardt closed this 10 minutes ago

You know how to confuse people :-)
