### ISSUE TITLE
Change a job after it has been added

### ISSUE THREAD

**Issue by HeikoTietze** [opensourcedesign/jobs#219]
Is it possible to edit the accepted job? In http://opensourcedesign.net/jobs/jobs/2017-04-20-branding-for-libreoffice-60 the mailing list address designg@global.libreoffice.org is misspelled. It should be design@global.libreoffice.org.

**Comment by simonv3** [comment]
It is!

The document for the job is here: https://github.com/opensourcedesign/jobs/blob/gh-pages/jobs/2017-04-20-branding-for-libreoffice-60.md

It's just a simple markdown file that gets rendered by github to display its content. 

You can edit it by clicking on the "pencil" icon in the top right corner of the file container. That will take you to this page: https://github.com/opensourcedesign/jobs/edit/gh-pages/jobs/2017-04-20-branding-for-libreoffice-60.md. You can then change whatever you want about it. At the bottom of that page - in short "commit changes" means "save". It's also best practice to toggle the "Create a new branch for this commit and start a pull request", that way the changes can be reviewed by others. 

This is the case for all jobs (and even all files!) on our website.  

I've also gone ahead and made the actual fix, but feel free to play around with that functionality!

**Comment by HeikoTietze** [comment]
Thanks, that WORKSFORME (though it's not the easiest tool).

**Comment by simonv3** [comment]
Haha, yeah it's a bit complex. It's how we're avoiding hosting costs. I think there's some things we can use instead to make editing of jobs easier, but there's a lot of overhead. Maybe something we'll solve at the summit?
