### ISSUE TITLE
Redesign of the Apache Maven website

### ISSUE THREAD

**Issue by evalica** [opensourcedesign/jobs#246]
The purpose of this issue is to gather deliverables and feedback for this [PR](https://github.com/opensourcedesign/jobs/pull/235), that wants the redesign of the [Apache Maven](http://maven.apache.org/) website.

Since discussions can happen on multiple channels, this issue should gather the design ideas so they are publicly available for anyone interested in the subject. 

* Current design
<a href="http://maven.apache.org/"><img src="https://user-images.githubusercontent.com/629552/29722274-cc748cce-89c8-11e7-8b63-31c2ac2d1e0d.png" width="270px"></a>  <img src="" width="270px">

* (i1) Homepage + Documentation Skin mockup, [more screenshots](http://www.xwiki.org/xwiki/bin/view/Blog/DocumentationFlavorExample)
<a href="http://www.xwiki.org/xwiki/bin/download/Blog/DocumentationFlavorExample/maven_homepage.png"><img src="http://www.xwiki.org/xwiki/bin/download/Blog/DocumentationFlavorExample/maven_homepage_partial.png" width="270px"></a>  <a href="http://www.xwiki.org/xwiki/bin/download/Blog/DocumentationFlavorExample/maven_doc.png"><img src="http://www.xwiki.org/xwiki/bin/download/Blog/DocumentationFlavorExample/maven_doc_partial.png" width="270px"></a>

* (i2) Homepage content alternative wireframe
<img src="https://user-images.githubusercontent.com/629552/29722662-5df40570-89ca-11e7-8d08-127c4220f81c.png" width="270px">  <img src="" width="270px">

* i...

It’s also very important that we better define what is the purpose and target of this redesign.
Please provide your feedback and ideas.

**Comment by sogen** [comment]
Logo too?

**Comment by rfscholte** [comment]
@sogen we've already tried to launch a new logo, but I think we can do better. A new website would be a great moment to have a new logo as well and to make them in line with each other.

**Comment by khmarbaise** [comment]
@rfscholte agreed. Yes get all parts into a single outline would be great..

**Comment by rfscholte** [comment]
Java9 is released, there are probably still some related activities for me, but I hope I can pick up this issue as well.

So let's sum up several things which are important to me:
- focus on desktop usage
- main information (will make a list of this) should be accessable by link without scrolling when using the most used resolution.
- focus on basic Maven users using the site as reference documentation. 
- Don't scare away newbies. There should be a clear recognizable part of the screen getting the attention for newbies so they can find there way with ease.

**Comment by itsN1X** [comment]
redesign: wip?

**Comment by nrizvi** [comment]
I am interested in helping anyway I can with this! Let me know if help is still needed :)

**Comment by jellynina** [comment]
I'd like to participate this issue as well. Please tell me if I can help.

**Comment by simonv3** [comment]
@evalica does it make sense to move this to our forum?

**Comment by 0x48piraj** [comment]
@jancborchardt 
This issue should be closed, I think. :confused: 
I'm referring to **Issue** #207 

> Please open all issues pertaining to the job board at https://github.com/opensourcedesign/opensourcedesign.github.io/issues
Thanks! :)

**Comment by jancborchardt** [comment]
@0x48piraj as @simonv3 said we could move it to the forum. However let's have @evalica decide it as she opened the issue and it's still active. :)

**Comment by evalica** [comment]
We can move the discussion in the forum. Is there a way to automatically create the forum entry from the job post? or do we need to do it manually? 
Besides the mockups listed here I didn't had the time to further work on the proposal, so any help/ideas/feedback/work is appreciated. 
The issue was done before us starting creating entries in the forum, so if we can discuss there is great, as long as the discussions continue.

**Comment by evalica** [comment]
Ok, so I've found the forum entry. It's https://discourse.opensourcedesign.net/t/jobs-redesign-maven-website/394. I'm going to close this issue and let's talk there. Thanks.
