### ISSUE TITLE
Distribution of job listings

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/jobs#25]
Once this is approved and ready to go, I would love to include a couple of job posting from here every week in [UX Weekly](http://uxwkly.com/). 

Would everyone be okay with that? Any other places these could be synced to?

**Comment by ei8fdb** [comment]
I think our jobs should be published far and wide. Do we still want to make this happen?

**Comment by simonv3** [comment]
Yeah, I don't really run UX Weekly anymore, but if we could get them in other newspapers. Maybe the Changelog?

**Comment by evalica** [comment]
Not sure what's the status with this issue. The problem I see is that our jobs start to get deprecated and with nobody having the time to mark them as closed or still relevant. Also our "absorption" power is limited and if can't help those organizations, they might not see the value in listing job posts anymore (but that's another topic).

**Comment by simonv3** [comment]
I think it's something worth reaching out to people about. We could do a "new on the osd job board" rather than a "searching for" job list.

**Comment by jancborchardt** [comment]
@simonv3 I think that’s an excellent idea! Are you in contact with UX Weekly?

I’ll just close this issue cause we want to have all issues related to the website (including job board) in our website issue tracker at https://github.com/opensourcedesign/opensourcedesign.github.io/issues (less confusion where issues are ;) – please reopen there. :)

**Comment by simonv3** [comment]
I ran UX Weekly for a while but haven't in a year. It's dead :(
