### ISSUE TITLE
Differentiation of "Jobs" and "Projects"

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/jobs#37]
During recent hack session with @simonv3 in Berlin, we discussed the idea of where is best to show / outline "projects" that OSD is building such as [Sick](https://github.com/opensourcedesign/slick). One of the big things, is that a project might involve funding. A few of the details that should added to a project as opposed to a simple job posting are:
- Project State (proposed, bidding, planning, creating, incomplete, finished)
- Proposed Budget (none, currency amount)
- Funding (met, needed, supplemental)
- Proposed Team (usernames)
- Outline of Work
- Deliverables
- ...etc...

@bradfrost brings up this idea of a [Project Hubs](http://24ways.org/2013/project-hubs/) that sort of charts all the stuff pertaining to a project in a nice visual timeline like this:

![food-bank-timeline](https://cloud.githubusercontent.com/assets/48677/7813591/94acdfa6-03bc-11e5-817f-3c74172643b0.png)

I think it would be awesome to show something like this for our "Projects" that we are developing and through the various states a project is at.

**Comment by simonv3** [comment]
@bnvk just to clarify, are you talking about merging the two repositories?

**Comment by bnvk** [comment]
@simonv3 yes, didn't we agree it is undesirable to have this many repositories as well two differing schemas (for Jobs & Projects)? That was my understanding and it made a bunch of sense at the time :)

**Comment by simonv3** [comment]
@bnvk Yep! Just wanted to confirm. I wonder how we can store a timeline for a project in data somehow rather than hardcoding it in HTML.

**Comment by ei8fdb** [comment]
Given the "a better jobs board" issue #91, has this now been taken care of?

Can this issue be closed, and superseded by #91?

**Comment by bnvk** [comment]
@ei8fdb not so much superseded by, but rather entirely different, but should probably be closed or refashioned. What I was always envisioning for the **Projects** page / section was a some sort of hybrid between a job posting + timeline of work + something snazy like @jancborchardt  has on [his website](http://jancborchardt.net) which he and I recently discussed adding to the OSD site. However, I think closing this makes sense as my idea needs to be given more thought and probably re-opened / filed elsewhere!
