### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by una** [opensourcedesign/jobs#4]
Didn't know where to post this issue -- but we need a logo :)

**Comment by pfefferle** [comment]
We should create a "project" repo to collect ideas/bugs

**Comment by jancborchardt** [comment]
We’re now discussing / sketching at https://github.com/opensourcedesign/opensourcedesign.github.io/issues/18, so closing this. :)

**Comment by simonv3** [comment]
@jancborchardt thanks for keeping the repos clean :)
