### ISSUE TITLE
Staticman errors "too many requests at this timeframe"

### ISSUE THREAD

**Issue by elioqoshi** [opensourcedesign/jobs#400]
I get an error when trying to submit a job posting:

```

error |  
-- | --
text | "Too many requests in this time frame."
nextValidRequestDate | "2019-06-09T15:45:52.084Z"

```

@m1guelpf could you have a look at this? It seems problematic to lose a job posting draft because of this error.

**Comment by jancborchardt** [comment]
Should be fixed through https://github.com/opensourcedesign/jobs/pull/438 :)
