### ISSUE TITLE
Error when submitting the job-form

### ISSUE THREAD

**Issue by tboeckmann** [opensourcedesign/jobs#410]
I have tried several times to submit a job on https://opensourcedesign.net/jobs/job-form/, but the resulting page gives an application error on Heroku:

![image](https://user-images.githubusercontent.com/2022378/67904551-9665ca00-fb66-11e9-9ad6-da543deda28d.png)

(URL is https://api.staticman.net/v2/entry/opensourcedesign/jobs/master/jobs)

**Comment by evalica** [comment]
Last successful job post creation was on 2019-09-27. I don't know what could have broken the form.

**Comment by ei8fdb** [comment]
I've just tried to post a test job posting and it gave me a successful post-submission message "Thanks for submitting your job!", but I've not seen the PR email yet. 

I can try it again later on and see if I can replicate @tboeckmann's issue.

@tboeckmann did you retry the submission?

**Comment by tboeckmann** [comment]
@ei8fdb Thanks- I just resubmitted the form with the exact same fields and it was successful.

Could you actually delete that post? I had to go elsewhere to kick off the process.

Heroku logs might show the reason for failure, otherwise, it seems the issue has gone away for now.
