### ISSUE TITLE
Scribus / Indigo: improve the new "Color Selection" panel

### ISSUE THREAD

**Issue by aoloe** [opensourcedesign/jobs#416]
(For some context see the OpenSourceDesign Forums: [Scribus and the Indigo project](https://discourse.opensourcedesign.net/t/scribus-and-the-indigo-project/1350))

_Indigo_  suggests a button with the current color and a popup panel that allows the selection and creation of colors.

![indigo-panel-lines](https://user-images.githubusercontent.com/1857016/69330862-0fcb7680-0c54-11ea-9ac3-2a9987c552ed.png)

![indigo-popup-colors](https://user-images.githubusercontent.com/1857016/69330870-15c15780-0c54-11ea-8ddd-7d1a41ec42b3.png)

You can see the context [in this slide](https://docs.google.com/presentation/d/1JRs-9VUaZGjG3Dvyci2DCpwIpYQLR8IZv485hjujdEk/view#slide=id.g1b2d6150d9_0_29)

I see some room for improvement:

- Picking a color will be a two clicks action.
- After having clicked on the color button, the most likely action is to pick an existing color. But the list of colors is far away.

Please help me create a "job" description for the job board by adding notes in this ticket or [editing the description on CodiMd](https://demo.codimd.org/RvDkPw2wQc60eu07I1fYTg#)

**Comment by jdittrich** [comment]
My suggestions for this job would be having 3 subtasks:
* Write down 2-3 usecases in which context people would use color selection (output: Text)
* Evaluate how other software solves color selection and what we could learn from them (output: table with comparison and notes)
* Evaluate the UI suggestion for indigo in the light of the usecases and of what we learned in the competition-review. Make appropriate suggestions, communicated visually.

**Comment by jancborchardt** [comment]
We should move the discussion to the forum to stay in one place :) → @jdittrich mind to repost your reply over there, @aoloe linked it above.

(And thanks for making me notice that the issue noting no issues should be opened here is closed and unpinned – see https://github.com/opensourcedesign/jobs/issues/207 :)
