### ISSUE TITLE
Scribus / Indigo: Provide symbolic icons 

### ISSUE THREAD

**Issue by aoloe** [opensourcedesign/jobs#417]
(For some context see the OpenSourceDesign Forums: [Scribus and the Indigo project](https://discourse.opensourcedesign.net/t/scribus-and-the-indigo-project/1350))

For the Indigo project we are introducing new icons.

We need one or more persons to:

- improve the temporary icons,
- if possible even creating the new icons JIT during the creation of the dialogs,
- going through the icons and make sure that there are no missing icons
- complete the dark theme

Please help me create a "job" description for the job board by adding notes in this ticket or [editing the description on CodiMd](https://demo.codimd.org/6k4eY3xmRwOcC36LcoZ7vQ#)

**Comment by jancborchardt** [comment]
Same as https://github.com/opensourcedesign/jobs/issues/416#issuecomment-595617493, discussions should happen on the forum. :)

If you have a job to post, we are about to fix the Job board via https://github.com/opensourcedesign/jobs/pull/438 and afterwards posting issues should work again. :)
