### ISSUE TITLE
Update the Readme.MD file to explain the current flow.

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/jobs#44]
The current Readme.MD says that you should create jobs via issues. Nah.

**Comment by ei8fdb** [comment]
This has been done, right? The README has [3 different "submit a job"](https://github.com/opensourcedesign/jobs/blob/gh-pages/README.md#submit-a-job) flow.

If this is correct, then we can close this?

Alternatively, isn't this being superseded by the "a better jobs board" form from #91?

If so, we need to update the README, again :)

**Comment by simonv3** [comment]
Yeah, lets close this in lieu of #91.
