### ISSUE TITLE
Design Update to the Gmail-Conversation-View addon for Thunderbird

### ISSUE THREAD

**Issue by elioqoshi** [opensourcedesign/jobs#55]
Hi guys!
We (me and some other designers at Mozilla) have started work to update the UI and UX of the Gmail-Conversation-View addon for Thunderbird. It's going pretty well but we need your help here. Check out this issue where we are trying to move forward (I'm still trying to get used to GitHub, bad habits)

https://github.com/protz/GMail-Conversation-View/issues/967#issuecomment-120551084

We would love to call it Convo or Convi. Attached the logo proposal and 2 mockups
![convo](https://cloud.githubusercontent.com/assets/5436686/9845639/c42ee384-5acc-11e5-9570-51e207c3f40b.jpg)
![1](https://cloud.githubusercontent.com/assets/5436686/9845643/c89964bc-5acc-11e5-9c9a-c078ce6c0fc5.jpg)
![2](https://cloud.githubusercontent.com/assets/5436686/9845644/c8d20394-5acc-11e5-8a2e-b9c6fea23d8a.jpg)

**Comment by bnvk** [comment]
@elioqoshi heya, cool stuff- I didn't know you worked on anything Thunderbird related at Mozilla. A few thoughts off the top of my head:

- Consider getting the powers that be to make this default or built into Thunderbird, this is how most modern email clients do things and having to install a plugin (which often leads to a far more buggy experience than default app features) is too much for most users. 
- It looks like you're showing previews within the the "search" or "list of different messages from different senders" I'd urge away from doing this and only show full messages in a "message thread" view- at least that's the approach I took on Mailpile.

You should also checkout the [Patterns - email](https://github.com/opensourcedesign/patterns/tree/master/email) folder I made awhile ago for inspiration- I collected lots of examples of "well designed" email clients and what they were doing with the UI

**Comment by jancborchardt** [comment]
Yeah, good to see that! One of the biggest possible improvements to that would be to add people’s profile pictures to that. (Source from the Contacts, or Gravatar, or elsewhere.)

**Comment by simonv3** [comment]
Good job on getting that conversation started. I agree with @bnvk - you should try to get these design considerations working up the Thunderbird chain. 

This looks great, though my first impression on the branding was that it looks like Windows 8 things. Consider that when using those colors and diagonals / straight edges. Not that big of a problem though in and of itself. The designs are clean and well put together. 

Is this a desktop app or a browser client? Do people know to look for the "new email" button in on those clients (bottom right). I know that's a familiar pattern in Android, but I'm not sure I would look there on a desktop client.

**Comment by elioqoshi** [comment]
@bnvk Yep, I love Thunderbid and am not happy with the situation at Mozilla (we are not considering it as one of our current products)

Integrating it on default into Thunderbird is pretty well possible once it is good enough quality. They did the same with the Lightning calendar in Thunderbird 38.

Regarding the second point of yours: I have not tweaked a lot on the UX, so the preview you mentioned is already in the existing addon. I focused more on the UI but we might tweak the UX and some patterns also if we think that's the way to go. Would love to have your suggestions based on your experiences from Mailpile.

@jancborchardt good idea! But what if only a few people use avatars? Maybe avatars should be optional? Maybe we can add avatars in a later version?

@simonv3 I tried to keep the same structure as the existing addon, yet redesigning it with having Material Design in mind. It might not look convincingly classic Google Material Design, but I neither think that's the goal.

This is for Thunderbird, so it's a desktop app.
Not sure if people "know" about the Material "Power" button, but it's present in a lot of Google services, also on Desktop, not only on Android. 
Is there another pattern you would suggest to include:

-Forward
-Reply in a new window
-Reply all in a new window

Would love to hear your thoughts!

**Comment by bnvk** [comment]
@jdittrich cool. On the Avatar point, I fully agree with @jancborchardt on this and suggest you push really hard for this internally- there is loads of data why avatars make people use (and addicted) to interfaces more than communication platforms without.
 
However, you bring up a good point about not that many people having avatars- this should be taken into account and a solution offered, like on creating a user profile, you upload a picture, then on exchanging contact with someone you can send them a vCard with all your info.

Checkout this proposal, which deals with more than just avatars, but is something we came up with on Mailpile called [SuperContacts](https://github.com/mailpile/Mailpile/wiki/Super-Contacts)

**Comment by elioqoshi** [comment]
@bnvk We could go on with Gravatar, LibreAvatar or similar services to get the avatar from. Offering a backup solution could be added later I guess

**Comment by elioqoshi** [comment]
@bnvk @simonv3 @jancborchardt and others, check this out:
https://github.com/protz/GMail-Conversation-View/issues/967#issuecomment-140350157

**Comment by belenbarrospena** [comment]
I really like that last one. My only complain is the icon-only approach to actions (a pet peeve of mine, because I have goldfish memory and I can never remember what they mean). Do the icons have a tooltip on hover with a text label?

Other than that, neat work :)

**Comment by elioqoshi** [comment]
@belenbarrospena Yeah I totally get that. There will be a tooltip on hover of course, in fact it's needed in the current version of the addon too, as the icons are even less self explainable.

**Comment by bnvk** [comment]
@eliqoshi nice, looking much better IMO :-) you might want to consider doing one of the following:

- adding a non-gendered outline of a person as a placeholder
- the colored circle with first letter of name for icons with no avatar (like Material design does)

**Comment by elioqoshi** [comment]
@bnvk Right, not sure how I didn't think of that! :)

**Comment by elioqoshi** [comment]
@bnvk Looking quite solid now I think! Thanks for the suggestion!
![v4](https://cloud.githubusercontent.com/assets/5436686/9877179/80f6521a-5bbb-11e5-9662-46223fdc896b.jpg)

**Comment by elioqoshi** [comment]
Got also the logo going :)

![logo](https://cloud.githubusercontent.com/assets/5436686/9877454/3552ccd8-5bbd-11e5-9a0f-6005109f3749.jpg)

**Comment by jancborchardt** [comment]
@elioqoshi great stuff! :) It’s good to share UI concepts between Thunderbird, Mailpile and [ownCloud Mail](https://github.com/owncloud/mail/). :) Looks much better with the avatars, and the placeholder we do pretty much like that as well.

**Comment by elioqoshi** [comment]
Thanks @jancborchardt ! Would you mind chipping into the discussion here?
https://github.com/protz/GMail-Conversation-View/issues/967#issuecomment-140461318

**Comment by bnvk** [comment]
Closing this, as it's not active for over a year now. @elioqoshi if you want, you can add these to [patterns  repo](/opensourcedesign/patterns). It would be cool to keep a collection of your work 😉

**Comment by elioqoshi** [comment]
Technically there is progress right now on this, just not by people associated on OSD (apart me). I think we should be able to wrap this up in the coming weeks.
