### ISSUE TITLE
GalliumOS Design Help

### ISSUE THREAD

**Issue by hugegreenbug** [opensourcedesign/jobs#58]
I'm starting a new Linux distribution that is optimized for ChromeOS devices called GalliumOS. It is based on Xubuntu, but will include custom changes and software for ChromeOS devices.

I would prefer to have someone join our team. These are the tasks I'm in need of help with right now:

1. Logo. We have one, but it may need some refinement.
2. Default look. We can work with an existing theme.
3. Website design. We have web programmers that can implement the design.

Thanks. We have an irc channel, #galliumos, on freenet.

**Comment by razetime** [comment]
@hugegreenbug, Your project seems very interesting.
Why don't you pull request, to add an open source job?

**Comment by simonv3** [comment]
This is now on the site: http://opensourcedesign.net/jobs/jobs/2015-10-06-15-galliumos.html

**Comment by elioqoshi** [comment]
@hugegreenbug I'd be interested to contribute!

**Comment by elioqoshi** [comment]
First proposal in full color and monochrome. What do you think?
![1](https://cloud.githubusercontent.com/assets/5436686/10416373/eebcff0c-7014-11e5-89df-2192f7de636a.jpg)

**Comment by hugegreenbug** [comment]
Elio,

Wow. This is really great. I'm going to run it by the rest of the team to
see what they say, but I think are going to like it too. Thank you so much.

Hugh

**Comment by elioqoshi** [comment]
Thank you @hugegreenbug ! Your project looks really promising, would love to further contribute :)

**Comment by elioqoshi** [comment]
P.S: In true open source fashion, I used Open Sans as the typeface for the logo, which is an open source font :)

**Comment by elioqoshi** [comment]
Here is another version with 45` rotation. Which one do you prefer?
![2](https://cloud.githubusercontent.com/assets/5436686/10417246/e1e5172c-7034-11e5-978b-79e9fe700984.jpg)

**Comment by bnvk** [comment]
@elioqoshi nice job! The concept renders great as color or
monochrome. I'm actually quite torn if I like the rotated or
straight version more. I think I'm 55% more keen on the straight
version- as it allows the nice swirl to shine more since it's
bigger.

**Comment by elioqoshi** [comment]
@bnvk Thanks Brennan! Yeah, I prefer that a tiny bit more either. Here is the refined version.
![1-01](https://cloud.githubusercontent.com/assets/5436686/10417663/1f494afc-7044-11e5-9584-1af2ebacbafc.jpg)

**Comment by elioqoshi** [comment]
Little bonus (desktop wallpaper)
![desktop1](https://cloud.githubusercontent.com/assets/5436686/10417765/4d69eefc-7047-11e5-9ba5-01b5a3f46dd7.jpg)

**Comment by elioqoshi** [comment]
aaand another one (this is public domain) 
![wallpaper gallium](https://cloud.githubusercontent.com/assets/5436686/10417783/f8132634-7047-11e5-8adb-dd732cff0821.jpg)

**Comment by elioqoshi** [comment]
another abstract nature one (stairs) also public domain
![stairs wallpaper](https://cloud.githubusercontent.com/assets/5436686/10417867/05e1e7ca-704b-11e5-8169-707b40ac40d5.jpg)

**Comment by elioqoshi** [comment]
and maybe this too 
![desktop4](https://cloud.githubusercontent.com/assets/5436686/10417878/4fc3a842-704b-11e5-8eab-265eab956f7f.jpg)

**Comment by hugegreenbug** [comment]
Elio,

This is really amazing. All of use really like the logos. The wallpapers
are also great.

We would absolutely love more of your help. You can find us in #galliumos
on freenode.net. You can also email me directly: hugegreenbug@gmail.com.

Hugh

**Comment by hugegreenbug** [comment]
I think we all agree that the refined, non-rotated versions are our
favorites. There was a request for an svg version. Would that be possible?

Hugh

**Comment by elioqoshi** [comment]
@hugegreenbug So glad you like them! Feel free to add me to the GitHub organization, I will try to contribute here and there then :)
Adding the SVG in a few.

**Comment by elioqoshi** [comment]
Profile picture

![profile](https://cloud.githubusercontent.com/assets/5436686/10418268/91f0d9d2-7056-11e5-84fb-ef4a1c648f66.jpg)

**Comment by elioqoshi** [comment]
![mockup1](https://cloud.githubusercontent.com/assets/5436686/10418350/36507478-7058-11e5-8221-3545e31f56a0.jpg)
quick desktop mockup with the Arc theme

**Comment by gillisig** [comment]
Wow @elioqoshi you are on a roll! Great work! :+1:

**Comment by elioqoshi** [comment]
Thank you @gillisig I'm having fun here :D

**Comment by jancborchardt** [comment]
Wooo awesome work @elioqoshi! :) For what it’s worth, I tend towards the rotated logo more since the straight one looks a bit like a mail envelope with a seal on it.

**Comment by simonv3** [comment]
:+1: this is awesome

**Comment by elioqoshi** [comment]
Thanks @jancborchardt and @simonv3 !
We went with the straight version, it was not an easy decision though :)

**Comment by evalica** [comment]
I see that the logo is used in production. Can we change the status of http://opensourcedesign.net/jobs/jobs/2015-10-06-15-galliumos.html from "Searching" to "Resolved"?

**Comment by simonv3** [comment]
And done!
