### ISSUE TITLE
Please be aware & test submissions before merging

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/jobs#71]
Hey y'all. Sorry, I just went kinda rogue and pushed some things without submitting a pull request. Reason being- I wanted to send a link to OSD and specifically the Jobs board and 5 or so links to postings didn't work. They would instead force a file download. The reason was because they did not end with a `.md` extension.

I assumed the submitter had used the "easy" option which was generating files with no extension. New contributors / submitters are probably going to overlook things like this- but maintainers / mergers should catch these sort of bugs. So please check the new listing you merge actually works :smile:

**Comment by duythien** [comment]
Sure, I forgot it :)

**Comment by simonv3** [comment]
Hey, thanks for catching this. This is probably partially my fault. I notice you also added the .md in the easy option and updated the Readme. Thanks for doing that too!
