### ISSUE TITLE
Navbar not opening/expanding in Mobile/Tablet Device

### ISSUE THREAD

**Issue by aishivam** [opensourcedesign/jobs#717]
below 767px min-width navbar is not expanding, here is the screenshot
![adobeopensource](https://user-images.githubusercontent.com/50539402/127034494-ff3e149e-fd42-4612-8e06-ed7bd9ce95bc.png)

**Comment by Erioldoesdesign** [comment]
You should move this issue to the other repo @aishivam https://github.com/opensourcedesign/opensourcedesign.github.io
