### ISSUE TITLE
Links in job posting often not links but plain text

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/jobs#73]
I went to some of the job postings and saw that many texts contain URLs, though they are not links. This makes it tedious for an interested viewer to go to these pages (makr-copy-paste-enter instead of clicking)

**Comment by jancborchardt** [comment]
Is there a way for Jekyll to automatically linkify all these links? @bnvk @simonv3

**Comment by jdittrich** [comment]
I am not into jekyll. Inferring from other, similar systems I suspect there is probably a switch or a post-processing-filter that could do this.

**Comment by simonv3** [comment]
If it's not possible in Jekyll we can probably run some JS on page load to find URLs and just change them into links. (I don't know of a jekyll feature that we control that would do this)

**Comment by bnvk** [comment]
yah like @simonv3 says, we can definitely do this with some JS quite easily. The Jekyll route would be better, but upon quick Google searching, no clearly defined modules. Maybe there is a flag on one the generators (kramdown, etc...) that exists though...

**Comment by ei8fdb** [comment]
I don't know if this has been sorted, I don't think so?

**Comment by simonv3** [comment]
Don't think so no.

**Comment by jancborchardt** [comment]
@jdittrich mind reopening that in our website issue tracker too?
A simple solution might be to reduce it from a textarea to an input field so we just linkify that one link in there.

I’ll just close this issue cause we want to have all issues related to the website (including job board) in our website issue tracker at https://github.com/opensourcedesign/opensourcedesign.github.io/issues (less confusion where issues are ;) – please reopen there. :)

**Comment by simonv3** [comment]
Hey @jancborchardt I get bringing all this together but I'm afraid that if you don't open the issue yourself these issues are going to get lost.
