### ISSUE TITLE
The jobs page does not contain the favicon on the browser tab.

### ISSUE THREAD

**Issue by daminisatya** [opensourcedesign/jobs#80]
Add a favicon to the browser tab. This is kind of inconsistent with the other pages.

**Comment by simonv3** [comment]
Thanks for opening the issue @daminisatya. 

This should be a pretty easy fix, as the favicon already exists and gets pointed to by the other repos.

**Comment by sudheesh001** [comment]
@simonv3 @daminisatya Could you please review #82 please :smile:
