### ISSUE TITLE
Add a space between <label>:<instance> items

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/jobs#89]
![screenshot 2016-05-16 07 54 40](https://cloud.githubusercontent.com/assets/485583/15295122/7e439bdc-1b3b-11e6-9f29-c44f87c8db70.png)

**Comment by razetime** [comment]
As far as I saw in the code, the layout jobs.html(if I'm correct), has necessary spacing.

**Comment by simonv3** [comment]
@razetime I moved the space to the other side of the closing `<label>` statement, and it looks like that fixed it.
