### ISSUE TITLE
Autopost to Twitter

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/jobs#90]
Use IFTTT?

**Comment by ei8fdb** [comment]
I've had a look through IFTTT and nothing jumps out based on whats possible there.

Some alternatives:

1. [Stackoverflow question "Is there a script that posts git commits to twitter?"](http://stackoverflow.com/questions/2652983/is-there-a-script-that-posts-git-commits-to-twitter). [Specifically](http://stackoverflow.com/a/2653090) [these answers](http://stackoverflow.com/a/15776348) look possible.
2. [Auto-posting static site updates from GitHub to Twitter with Zapier](http://zemanel.eu/auto-post-static-site-updates-from-github-to-twitter-with-zapier.html)
3. [Tweet new GitHub events - from Zapier](https://zapier.com/app/editor/template/11491)
4. [A collection of Zapier/Github/Twitter integrations](https://zapier.com/zapbook/github/twitter/)

**Comment by simonv3** [comment]
RSS to Twitter should be possible using IFTTT though? And we have an RSS feed. Zapier is definitely another course we can take.

**Comment by bnvk** [comment]
> RSS to Twitter should be possible using IFTTT though

This should absolutely be possible and sounds like best option to me as we don't need to filter GitHub events. However, I propose that we have multiple RSS feeds such as

- https://opensourcedesign.net/articles/feed.xml
- https://opensourcedesign.net/jobs/feed.xml
- https://opensourcedesign.net/events/feed.xml

Then we could have more granular control over things like auto-posting!

**Comment by simonv3** [comment]
I think we do! Though articles/feed.xml is just https://opensourcedesign.net/feed.xml

**Comment by simonv3** [comment]
Did anyone set up a IFTTT account for us already? It's telling me that `opensourcedesign` is already taken. 

@ei8fdb @elioqoshi @evalica @razetime

**Comment by evalica** [comment]
I don't know.

**Comment by bnvk** [comment]
Moved to opensourcedesign/opensourcedesign.github.io#85
